spring.application.name=barbershop

# config banco de dados postgreSql
spring.datasource.url=jdbc:postgresql://localhost:5433/barbershop_db
spring.datasource.username=postgres
spring.datasource.password=304613vh
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true